server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false   # 关闭 thymeleaf 的缓存设置
  rabbitmq:
    username: leyou
    password: leyou
    virtual-host: /leyou
    host: 192.168.10.131

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
# 生成静态页面存放的目录地址
ly:
  thymeleaf:
    destPath: D:\nginx-1.5.1\html\item
